name: "CI CD Test Action"
description: "Greets someone"
inputs:
  who-to-greet:
    description: "Who to greet"
    required: true

  sa_token:
    description: "SuperAnnotate access token"
    required: true

  sa_url:
    description: "SuperAnnotate URL"
    required: false

runs:
  using: "node20"
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        npm install
    - name: Run action
      shell: bash
      env:
        SA_TOKEN: ${{ inputs.sa_token }}
        SA_URL: ${{ inputs.sa_url }}
      run: |
        node pipe/pipe.js
